#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo [pre-commit] formatting staged files...
npm run format-staged
echo [pre-commit] done formatting staged files

git secrets --register-aws || (echo 'Please install git-secrets https://github.com/awslabs/git-secrets to check for accidentally commited secrets!' && exit 1)
git secrets --scan