name: NPM Packaging
on:
    push:
        branches: [main, dev, feature/*]
    pull_request:
        branches: [main, dev, feature/*]

jobs:
    build:
        name: Test public NPM packages
        runs-on: ubuntu-latest
        steps:
            - name: Sync Code
              uses: actions/checkout@v3
            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build all monorepo packages
              run: |
                  npm run compile
            - name: Pack public npm packages
              run: |
                  npm pack -w server/aws-lsp-codewhisperer -w server/aws-lsp-partiql -w server/aws-lsp-json -w server/aws-lsp-yaml -w server/aws-lsp-antlr4 -w core/aws-lsp-core -w chat-client
            - name: Create test package
              run: |
                  cd tests
                  npm install ../aws-lsp-codewhisperer-*.tgz ../aws-lsp-partiql-*.tgz ../aws-lsp-json-*.tgz ../aws-lsp-yaml-*.tgz ../aws-lsp-antlr4-*.tgz ../aws-lsp-core-*.tgz ../aws-chat-client-*.tgz
            - name: Test imports
              run: |
                  cd tests
                  npm run test
