name: Publish PartiQL Language Server to npmjs

on:
    push:
        tags:
            - 'lsp-partiql/v**'

jobs:
    publish:
        uses: ./.github/workflows/publish-to-npm.yaml
        with:
            workspace: 'server/aws-lsp-partiql'
        secrets: inherit
