name: Reusable Publish Package to npmjs workflow

on:
    workflow_call:
        inputs:
            workspace:
                required: true
                type: string

permissions:
    id-token: write # This is required for requesting the JWT
    contents: read # This is required for actions/checkout

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::935785792371:role/GithubNpmPublishAction
                  role-session-name: language-servers-github
                  aws-region: us-east-1
            - name: Get npm access token
              uses: aws-actions/aws-secretsmanager-get-secrets@v2
              with:
                  secret-ids: |
                      npmjs/github_automation
                  parse-json-secrets: true
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
                  scope: '@aws'
            - run: npm ci
            - run: npm run compile
            - run: npm publish --workspace ${{ inputs.workspace }}
              env:
                  NODE_AUTH_TOKEN: ${{ env.NPMJS_GITHUB_AUTOMATION_TOKEN }}
