name: Publish Codewhisperer Language Server to npmjs

on:
    push:
        tags:
            - 'chat-client/v**'

jobs:
    publish:
        uses: ./.github/workflows/publish-to-npm.yaml
        with:
            workspace: 'chat-client'
        secrets: inherit
