name: Publish JSON Language Server to npmjs

on:
    push:
        tags:
            - 'lsp-json/v**'

jobs:
    publish:
        uses: ./.github/workflows/publish-to-npm.yaml
        with:
            workspace: 'server/aws-lsp-json'
        secrets: inherit
