name: Publish Core Language Server utils package to npmjs

on:
    push:
        tags:
            - 'lsp-core/v**'

jobs:
    publish:
        uses: ./.github/workflows/publish-to-npm.yaml
        with:
            workspace: 'core/aws-lsp-core'
        secrets: inherit
