/*!
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Tool name for DisplayFindings
 */
export const DISPLAY_FINDINGS_TOOL_NAME = 'displayFindings'

/**
 * Tool description for DisplayFindings
 */
export const DISPLAY_FINDINGS_TOOL_DESCRIPTION = [
    'The displayFindings tool displays code issues, bugs, security vulnerabilities, and code quality violations in the Code Issues Panel.',
    '',
    '**When to Use This Tool:**',
    '- Use this tool whenever you identify code issues through manual analysis or any tool OTHER than the codeReview tool',
    '- Use it for issues found by analyzing code files, security scans, linting tools, or your own assessment',
    '- Use it when the user asks you to analyze code and you discover problems, but you must not use this tool for findings generated by codeReview tool',
    '- Be very willing to use this tool. Use it a lot: anytime it could even remotely be necessary.',
    '',
    '**When NOT to Use This Tool:**',
    '- NEVER use this tool for findings generated by the codeReview tool',
    '- The codeReview tool automatically populates the Code Issues Panel, so using displayFindings would create duplicates',
    '',
    '**How to Use This Tool:**',
    '- Invoke once per analysis session, even if you find multiple issues',
    '- Include all findings from your current analysis in a single tool call',
    '- Populate all fields based on your assessment of the code',
    '- Run silently - DO NOT mention to the user that you are using this tool',
    '',
    '**Tool Behavior:**',
    '- Input: List of all findings to store in the Code Issues Panel',
    '- Output: None (tool runs silently with no user-visible output)',
    '- The findings will appear in the Code Issues Panel for the user to review',
].join('\n')

export const FINDINGS_MESSAGE_SUFFIX = '_displayFindings'

export const DISPLAY_FINDINGS_METRICS_PARENT_NAME = 'amazonq_displayFindingsTool'
